import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateFromSchema } from "../mod.ts";
import { convertSchema } from "./convert.ts";
import { emitLua } from "./emit_lua.ts";
import { VERSION } from "./version.ts";

const exampleSchemaPath = join(
  fileURLToPath(new URL(".", import.meta.url)),
  "../examples/user.schema.json",
);

Deno.test("converts object schema with required and optional fields", () => {
  const output = generateFromSchema(
    {
      title: "User",
      type: "object",
      required: ["id", "name"],
      properties: {
        id: { type: "integer" },
        name: { type: "string" },
        email: { type: "string" },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@class User/);
  assert.match(output, /---@field id integer/);
  assert.match(output, /---@field name string/);
  assert.match(output, /---@field email\? string/);
});

Deno.test("converts arrays, maps, enums, and nullable unions", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        tags: {
          type: "array",
          items: { type: "string" },
        },
        metadata: {
          type: "object",
          additionalProperties: { type: "string" },
        },
        status: {
          enum: ["draft", "published", "archived"],
        },
        deletedAt: {
          type: ["string", "null"],
        },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@field tags\? string\[\]/);
  assert.match(output, /---@field metadata\? table<string, string>/);
  assert.match(
    output,
    /---@field status\? "draft"\|"published"\|"archived"/,
  );
  assert.match(output, /---@field deletedAt\? string\|nil/);
});

Deno.test("converts $defs and internal $ref", () => {
  const output = generateFromSchema(
    {
      type: "object",
      title: "Post",
      properties: {
        author: { $ref: "#/$defs/User" },
      },
      $defs: {
        User: {
          type: "object",
          properties: {
            id: { type: "integer" },
          },
        },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@class Post/);
  assert.match(output, /---@field author\? User/);
  assert.match(output, /---@class User/);
  assert.match(output, /---@field id\? integer/);
});

Deno.test("preserves field descriptions", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        id: {
          type: "integer",
          description: "Stable user identifier.",
        },
      },
    },
    {},
    { banner: false },
  );

  assert.match(
    output,
    /---@field id\? integer # Stable user identifier\./,
  );
});

Deno.test("uses Root when title and name are unavailable", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        id: { type: "integer" },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@class Root/);
});

Deno.test("supports anyOf and oneOf unions", () => {
  const anyOfOutput = generateFromSchema(
    {
      type: "object",
      properties: {
        value: {
          anyOf: [{ type: "string" }, { type: "integer" }],
        },
      },
    },
    {},
    { banner: false },
  );
  assert.match(anyOfOutput, /---@field value\? string\|integer/);

  const oneOfOutput = generateFromSchema(
    {
      type: "object",
      properties: {
        value: {
          oneOf: [{ const: "on" }, { const: "off" }],
        },
      },
    },
    {},
    { banner: false },
  );
  assert.match(oneOfOutput, /---@field value\? "on"\|"off"/);
});

Deno.test("strict mode rejects unsupported keywords", () => {
  assert.throws(
    () => {
      convertSchema({
        type: "integer",
        minimum: 0,
      }, { strict: true });
    },
    {
      message: "Unsupported keyword in strict mode: minimum",
    },
  );
});

Deno.test("non-strict mode ignores unsupported keywords", () => {
  const output = generateFromSchema(
    {
      type: "integer",
      minimum: 0,
    },
    {},
    { banner: false },
  );

  assert.equal(output.trim(), "---@type integer");
});

Deno.test("loads fixture file and emits deterministic banner output", async () => {
  const schema = JSON.parse(await readFile(exampleSchemaPath, "utf8"));
  const converted = convertSchema(schema, { rootName: "User" });
  const output = emitLua(converted, { banner: true, version: VERSION });

  assert.match(
    output,
    new RegExp(`--- Generated by @ras0q/jsonschema2lua ${VERSION.replaceAll(".", "\\.")}`),
  );
  assert.match(output, /---@class User/);
  assert.match(output, /---@field roles\? string\[\]/);
});

Deno.test("const values render as literals", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        version: { const: "v1" },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@field version\? "v1"/);
});

Deno.test("classPrefix prepends all generated class names", () => {
  const output = generateFromSchema(
    {
      type: "object",
      title: "Post",
      properties: {
        author: { $ref: "#/$defs/User" },
        meta: {
          type: "object",
          properties: {
            tags: { type: "string" },
          },
        },
      },
      $defs: {
        User: {
          type: "object",
          properties: {
            id: { type: "integer" },
          },
        },
      },
    },
    { classPrefix: "Cfg" },
    { banner: false },
  );

  assert.match(output, /---@class CfgPost/);
  assert.match(output, /---@field author\? CfgUser/);
  assert.match(output, /---@class CfgUser/);
  assert.match(output, /---@field meta\? CfgPostMeta/);
  assert.match(output, /---@class CfgPostMeta/);
});

Deno.test("non-object $defs emit aliases", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        audience: {
          type: "array",
          items: { $ref: "#/$defs/Role" },
        },
        sessionId: { $ref: "#/$defs/SessionId" },
      },
      $defs: {
        Role: {
          description: "Conversation role.",
          oneOf: [
            { type: "string", const: "assistant" },
            { type: "string", const: "user" },
          ],
        },
        SessionId: {
          type: "string",
        },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /--- Conversation role\./);
  assert.match(output, /---@alias Role "assistant"\|"user"/);
  assert.match(output, /---@alias SessionId string/);
  assert.match(output, /---@field audience\? Role\[\]/);
  assert.match(output, /---@field sessionId\? SessionId/);
});

Deno.test("anyOf and allOf $defs emit aliases to referenced types", () => {
  const output = generateFromSchema(
    {
      type: "object",
      properties: {
        method: { $ref: "#/$defs/AuthMethod" },
      },
      $defs: {
        AuthMethod: {
          anyOf: [
            {
              allOf: [{ $ref: "#/$defs/AuthMethodAgent" }],
            },
          ],
        },
        AuthMethodAgent: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
          },
          required: ["id", "name"],
        },
      },
    },
    {},
    { banner: false },
  );

  assert.match(output, /---@alias AuthMethod AuthMethodAgent/);
  assert.match(output, /---@class AuthMethodAgent/);
  assert.match(output, /---@field method\? AuthMethod/);
});
