import type {
  ConvertResult,
  EmitOptions,
  LuaClass,
  LuaField,
  LuaType,
} from "./types.ts";

const DEFAULT_VERSION = "0.1.0";

/**
 * Render converted schema data as LuaLS-compatible annotation lines.
 * Output is deterministic: classes are sorted alphabetically by name.
 */
export function emitLua(
  result: ConvertResult,
  options: EmitOptions = {},
): string {
  const lines: string[] = [];
  const banner = options.banner ?? true;
  const version = options.version ?? DEFAULT_VERSION;

  if (banner) {
    lines.push(`--- Generated by @ras0q/jsonschema2lua ${version}`);
    lines.push("--- Do not edit manually.");
    lines.push("");
  }

  for (const luaClass of result.classes) {
    lines.push(...emitClass(luaClass));
    lines.push("");
  }

  if (result.rootType) {
    lines.push(`---@type ${renderType(result.rootType)}`);
  }

  while (lines.length > 0 && lines.at(-1) === "") {
    lines.pop();
  }

  return lines.join("\n") + (lines.length > 0 ? "\n" : "");
}

function emitClass(luaClass: LuaClass): string[] {
  const lines: string[] = [`---@class ${luaClass.name}`];
  for (const field of luaClass.fields) {
    lines.push(emitField(field));
  }
  return lines;
}

function emitField(field: LuaField): string {
  const optionalMarker = field.optional ? "?" : "";
  const typeText = renderType(field.type);
  const description = field.description
    ? ` # ${field.description.replace(/\n/g, " ")}`
    : "";
  return `---@field ${field.name}${optionalMarker} ${typeText}${description}`;
}

function renderType(type: LuaType): string {
  switch (type.kind) {
    case "any":
      return "any";
    case "nil":
      return "nil";
    case "primitive":
      return type.name;
    case "literal":
      return renderLiteral(type.value);
    case "array":
      return `${renderType(type.item)}[]`;
    case "map":
      return `table<${renderType(type.key)}, ${renderType(type.value)}>`;
    case "union":
      return type.types.map(renderType).join("|");
    case "ref":
      return type.name;
    case "class":
      return type.name;
  }
}

function renderLiteral(value: string | number | boolean): string {
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return String(value);
}
