import type {
  ConvertResult,
  EmitOptions,
  LuaAlias,
  LuaClass,
  LuaField,
  LuaType,
} from "./types.ts";
import { VERSION } from "./version.ts";

type NamedDefinition =
  | { kind: "alias"; alias: LuaAlias }
  | { kind: "class"; luaClass: LuaClass };

/**
 * Render converted schema data as LuaLS-compatible annotation lines.
 * Output is deterministic: definitions are sorted alphabetically by name.
 */
export function emitLua(
  result: ConvertResult,
  options: EmitOptions = {},
): string {
  const lines: string[] = [];
  const banner = options.banner ?? true;
  const version = options.version ?? VERSION;

  if (banner) {
    lines.push(`--- Generated by @ras0q/jsonschema2lua ${version}`);
    lines.push("--- Do not edit manually.");
    lines.push("");
  }

  const definitions: NamedDefinition[] = [
    ...result.aliases.map((alias) => ({ kind: "alias" as const, alias })),
    ...result.classes.map((luaClass) => ({
      kind: "class" as const,
      luaClass,
    })),
  ].sort((a, b) => definitionName(a).localeCompare(definitionName(b)));

  for (const definition of definitions) {
    if (definition.kind === "alias") {
      lines.push(...emitAlias(definition.alias));
    } else {
      lines.push(...emitClass(definition.luaClass));
    }
    lines.push("");
  }

  if (result.rootType) {
    lines.push(`---@type ${renderType(result.rootType)}`);
  }

  while (lines.length > 0 && lines.at(-1) === "") {
    lines.pop();
  }

  return lines.join("\n") + (lines.length > 0 ? "\n" : "");
}

function definitionName(definition: NamedDefinition): string {
  return definition.kind === "alias"
    ? definition.alias.name
    : definition.luaClass.name;
}

function emitAlias(alias: LuaAlias): string[] {
  const lines: string[] = [];
  if (alias.description) {
    lines.push(`--- ${alias.description.replace(/\n/g, " ")}`);
  }
  lines.push(`---@alias ${alias.name} ${renderType(alias.type)}`);
  return lines;
}

function emitClass(luaClass: LuaClass): string[] {
  const lines: string[] = [`---@class ${luaClass.name}`];
  for (const field of luaClass.fields) {
    lines.push(emitField(field));
  }
  return lines;
}

function emitField(field: LuaField): string {
  const optionalMarker = field.optional ? "?" : "";
  const typeText = renderType(field.type);
  const description = field.description
    ? ` # ${field.description.replace(/\n/g, " ")}`
    : "";
  return `---@field ${field.name}${optionalMarker} ${typeText}${description}`;
}

function renderType(type: LuaType): string {
  switch (type.kind) {
    case "any":
      return "any";
    case "nil":
      return "nil";
    case "primitive":
      return type.name;
    case "literal":
      return renderLiteral(type.value);
    case "array":
      return `${renderType(type.item)}[]`;
    case "map":
      return `table<${renderType(type.key)}, ${renderType(type.value)}>`;
    case "union":
      return type.types.map(renderType).join("|");
    case "ref":
      return type.name;
    case "class":
      return type.name;
  }
}

function renderLiteral(value: string | number | boolean): string {
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return String(value);
}
